[package]
name = "mcc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.95", features = ["backtrace"] }
clap = { version = "4.5.23", features = ["derive"] }
console = "0.15.10"
tempfile = "3.14.0"
thiserror = "2.0.11"
