name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build (release)
      run: cargo build --release

    - name: Unit tests
      run: cargo test

    - name: Integration tests
      run: ./tests/writing-a-c-compiler-tests/test_compiler ./target/release/mcc --chapter 8
        
